version: "3.8"

services:
  website:
    image: takuto-de:production
    build:
      target: production
    ports:
      - "127.0.0.1:8080:80"
    networks:
      - takuto-site

networks:
  takuto-site:
    name: "takuto-site"
