---
- name: Create application directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /opt/nginx-proxy
    - /opt/nginx-proxy/conf.d
    - /opt/nginx-proxy/vhost.d
    - /opt/nginx-proxy/html
    - /opt/nginx-proxy/certs
    - /opt/nginx-proxy/gcloud-dns
    - /opt/takuto-website
    - /opt/takuto-website/uploads

- name: Create Google Cloud DNS service account key file
  copy:
    content: "{{ gcloud_dns_service_account }}"
    dest: /opt/nginx-proxy/gcloud-dns/credentials.json
    mode: '0600'

- name: Copy docker-compose files to deployment directory
  copy:
    src: "{{ playbook_dir }}/../{{ item }}"
    dest: /opt/takuto-website/
    mode: '0644'
  loop:
    - "docker-compose.yml"
    - "docker-compose.prod.yml"


- name: Pull Docker image for the website
  community.docker.docker_image:
    name: "ghcr.io/takuto88/takuto-de:{{ website_version }}"
    source: pull
    force_source: yes
    state: present

- name: Run website with Docker Compose
  community.docker.docker_compose_v2:
    project_src: /opt/takuto-website
    state: present
    extra_args: "-f docker-compose.yml -f docker-compose.prod.yml"
  vars:
    EMAIL_FOR_CERTBOT: "{{ email_for_certbot }}"
    DOMAINS_STR: "{{ domains | join(',') }}"
    GCLOUD_DNS_PROJECT_ID: "{{ (gcloud_dns_service_account.project_id) if (gcloud_dns_service_account is mapping) else (gcloud_dns_service_account | from_json | json_query('project_id')) }}"
    GCLOUD_DNS_ZONE_NAME: "{{ gcloud_dns_zone }}"
