---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - ca-certificates
      - python3-pip
    state: present

- name: Add Docker repository
  deb822_repository:
    name: docker
    repos: "deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    architectures: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present

- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Install Docker Python module from Debian packages
  apt:
    name:
      - python3-docker
    state: present

- name: Ensure Docker service is enabled and started
  service:
    name: docker
    state: started
    enabled: yes
