---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - python3-pip
    state: present

- name: Add Docker GPG apt key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Determine architecture
  command: dpkg --print-architecture
  register: architecture
  changed_when: false

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch={{ architecture.stdout }}] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
    state: present

- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes

- name: Install Docker Python module from Debian packages
  apt:
    name:
      - python3-docker
    state: present

- name: Ensure Docker service is enabled and started
  service:
    name: docker
    state: started
    enabled: yes
