name: Push to GCR GitHub Action
on: [push]
jobs:
  build-and-push-to-gcr:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
    steps:
      - id: 'checkout'
        uses: actions/checkout@v3
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - id: 'build-and-push'
        uses: RafikFarhad/push-to-gcr-github-action@v5-beta
        with:
          registry: europe-west1-docker.pkg.dev
          project_id: takuto-de-site
          image_name: takuto/website
          image_tag: ${{ github.sha }}
          dockerfile: Dockerfile
          context: .
          target: production

  deploy:
    runs-on: ubuntu-22.04
    needs: build-and-push-to-gcr
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: ${{ secrets.GCLOUD_SERVICE_KEY }}
      - id: 'deploy'
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'website'
          image: 'europe-west1-docker.pkg.dev/takuto-de-site/takuto/website:${{ github.sha }}'
          region: 'europe-west1'