name: Deploy Website to Hetzner

on:
  workflow_dispatch:
    inputs:
      website_version:
        description: 'Docker image tag to deploy'
        required: false
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: "Hetzner VM / GCloud DNS"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible hcloud

      - name: Install Ansible collections
        run: ansible-galaxy collection install -r ansible/requirements.yml

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keygen -y -f ~/.ssh/id_rsa > ~/.ssh/id_rsa.pub
          ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

      - name: Deploy to Hetzner
        working-directory: ./ansible
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
          GCLOUD_DNS_SA: ${{ secrets.GCLOUD_DNS_SA }}
          SSH_KEY_NAME: ${{ vars.SSH_KEY_NAME }}
          SSH_PUBLIC_KEY: ${{ vars.SSH_PUBLIC_KEY }}
          WEBSITE_VERSION: ${{ github.event.inputs.website_version || 'latest' }}
          GCLOUD_DNS_ZONE: 'takuto-de'
        run: |
          ansible-playbook site.yml
